master:
  push:
    - imports: https://cnb.cool/ds6666.fun/blog/secret/-/blob/main/cos_envs.yml
    - stages:
        - name: update tencentyun-cos
          image: tencentcom/tencentyun-coscmd
          commands: |
            coscmd config -a $env.COS_SECRET_ID -s $env.COS_SECRET_KEY -b $env.COS_BUCKET_NAME -r $env.COS_BUCKET_REGION
            rm -rf .git
            coscmd upload -r ./ /